---
products:
  - name: pc
    price: 650
  - name: skate
    price: 20
  - name: nintendo
    price: 240
  - name: colunas
    price: 120
  - name: vinil
    price: 80
  - name: raspberry
    price: 100
  - name: bmx
    price: 300
  - name: camisola
    price: 20
buyers:
  - products:
      - name: pc
        quantity: 5
      - name: nintendo
        quantity: 3
      - name: bmx
        quantity: 2
    counterOfferStrategy: SMART
    patience: 100
  - products:
      - name: raspberry
        quantity: 7
      - name: vinil
        quantity: 10
      - name: colunas
        quantity: 2
    counterOfferStrategy: SMART
    patience: 40
  - products:
      - name: pc
        quantity: 1
      - name: skate
        quantity: 3
      - name: bmx
        quantity: 5
    counterOfferStrategy: RELTFT
    patience: 100
  - products:
      - name: nintendo
        quantity: 7
      - name: vinil
        quantity: 12
      - name: colunas
        quantity: 4
    counterOfferStrategy: ABSTFT
    patience: 100
  - products:
      - name: camisola
        quantity: 21
      - name: bmx
        quantity: 2
      - name: pc
        quantity: 3
    counterOfferStrategy: RELTFT
    patience: 100

sellers:
  - scamFactor: 50
    elasticity: 40
    offerStrategy: SMART
    pickingStrategy: SMART
    products:
      - name: pc
        quantity: 10
      - name: bmx
        quantity: 10
      - name: raspberry
        quantity: 10

  - scamFactor: 50
    elasticity: 30
    offerStrategy: ABSTFT
    pickingStrategy: SMART
    products:
      - name: pc
        quantity: 10
      - name: camisola
        quantity: 30
      - name: nintendo
        quantity: 10

  - scamFactor: 50
    elasticity: 20
    offerStrategy: RELTFT
    pickingStrategy: NAIVE
    products:
      - name: pc
        quantity: 10
      - name: vinil
        quantity: 50
      - name: colunas
        quantity: 20
      - name: nintendo
        quantity: 15

