---
products:
  - name: pc
    price: 650
  - name: skate
    price: 20
buyers:
  - products:
      - pc
    counterOfferStrategy: SMART
    patience: 80
  - products:
      - pc
    counterOfferStrategy: ABSTFT
    patience: 80
  - products:
      - pc
    counterOfferStrategy: RELTFT
    patience: 80
  - products:
      - pc
    counterOfferStrategy: ABSTFT
    patience: 80
  - products:
      - pc
    counterOfferStrategy: RELTFT
    patience: 80

sellers:
  - scamFactor: 50
    elasticity: 50
    offerStrategy: SMART
    pickingStrategy: SMART
    products:
      - pc

  - scamFactor: 50
    elasticity: 50
    offerStrategy: ABSTFT
    pickingStrategy: NAIVE
    products:
      - pc
  - scamFactor: 50
    elasticity: 50
    offerStrategy: RELTFT
    pickingStrategy: SMART
    products:
      - skate

