---
products:
  - name: pc
    price: 15
  - name: skate
    price: 20
buyers:
  - products:
      - pc
sellers:
  - credibility: 34
    products:
      - name: pc
        price: 15
  - credibility: 67
    products:
      - name: skate
        price: 20
      - name: pc
        price: 15
  - credibility: 100
    products:
      - name: skate
        price: 20
