---
products:
  - name: pc
    price: 650
  - name: skate
    price: 20
  - name: nintendo
    price: 240
  - name: colunas
    price: 120
  - name: vinil
    price: 80
  - name: raspberry
    price: 100
  - name: bmx
    price: 300
  - name: camisola
    price: 20
buyers:
  - products:
      - pc
      - nintendo
      - bmx
    counterOfferStrategy: SMART
    patience: 100
  - products:
      - raspberry
      - vinil
      - colunas
    counterOfferStrategy: SMART
    patience: 40
  - products:
      - pc
      - skate
      - bmx
    counterOfferStrategy: RELTFT
    patience: 100
  - products:
      - nintendo
      - vinil
      - colunas
    counterOfferStrategy: ABSTFT
    patience: 100
  - products:
      - camisola
      - bmx
      - pc
    counterOfferStrategy: RELTFT
    patience: 100

sellers:
  - scamFactor: 50
    elasticity: 40
    offerStrategy: SMART
    pickingStrategy: SMART
    products:
      - pc
      - bmx
      - raspberry

  - scamFactor: 50
    elasticity: 30
    offerStrategy: ABSTFT
    pickingStrategy: SMART
    products:
      - pc
      - camisola
      - nintendo

  - scamFactor: 50
    elasticity: 20
    offerStrategy: RELTFT
    pickingStrategy: NAIVE
    products:
      - pc
      - vinil
      - colunas
      - nintendo

