---
products:
  - name: pc
    price: 15
  - name: skate
    price: 20
buyers:
  - products:
      - pc
    counterOfferStrategy: test

  - products:
      - pc
    counterOfferStrategy: test

  - products:
      - pc
    counterOfferStrategy: test

  - products:
      - pc
    counterOfferStrategy: test
sellers:
  - scamFactor: 50
    elasticity: 14
    offerStrategy: test
    pickingStrategy: test
    products:
      - pc

  - scamFactor: 50
    elasticity: 9
    offerStrategy: test
    pickingStrategy: test
    products:
      - skate
      - pc
  - scamFactor: 50
    elasticity: 5
    offerStrategy: test
    pickingStrategy: test
    products:
      - skate
