---
products:
  - name: pc
    price: 15
  - name: skate
    price: 20
buyers:
  - products:
      - skate
    counterOfferStrategy: test

sellers:
  - scamFactor: 0
    elasticity: 14
    offerStrategy: test
    pickingStrategy: test
    products:
      - skate

