---
products:
  - name: pc
    price: 650
  - name: skate
    price: 20
buyers:
  - products:
      - pc
    counterOfferStrategy: test
    patience: 80
  - products:
      - pc
    counterOfferStrategy: test
    patience: 80
  - products:
      - pc
    counterOfferStrategy: test
    patience: 80
  - products:
      - pc
    counterOfferStrategy: test
    patience: 80
  - products:
      - pc
    counterOfferStrategy: test
    patience: 80

sellers:
  - scamFactor: 50
    elasticity: 50
    offerStrategy: turtle
    pickingStrategy: test
    products:
      - pc

  - scamFactor: 50
    elasticity: 50
    offerStrategy: test
    pickingStrategy: test
    products:
      - pc
  - scamFactor: 50
    elasticity: 50
    offerStrategy: test
    pickingStrategy: test
    products:
      - skate

